name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests=2.24.0
  - mlflow=2.1.1
  - pip:
      - wandb==0.13.9
      - git+https://github.com/XxRemsteelexX/NYC-Airbnb-ML-Pipeline.git#egg=wandb-utils&subdirectory=components
